export enum EventChannelList {
  EVENT_FOLLOWED = 'EVENT_FOLLOWED',
  EVENT_UNFOLLOWED = 'EVENT_UNFOLLOWED',
  PUBLISHER_FOLLOWED = 'PUBLISHER_FOLLOWED',
  SENT_FRIEND_REQUEST = 'SENT_FRIEND_REQUEST',
  ACCEPTED_FRIEND_REQUEST = 'ACCEPTED_FRIEND_REQUEST',
  EVENTS_FILTERS_CHANGED = 'EVENTS_FILTERS_CHANGED',
}

export type EventChannel = keyof (typeof EventChannelList);
