export enum QueryKey {
  FETCH_CATEGORIES = 'FETCH_CATEGORIES',
  FETCH_CATEGORY = 'FETCH_CATEGORY',
  FETCH_SUB_CATEGORIES = 'FETCH_SUB_CATEGORIES',
  FETCH_SUB_CATEGORY = 'FETCH_SUB_CATEGORY',
  FETCH_PRODUCTS = 'FETCH_PRODUCTS',
}
